pipeline{
    agent any
    stages{
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }
        stage("Clone Repo"){
            steps{
                sh "git clone https://github.com/shahsamarth46/simple-java-maven-app.git"
            }
        }
        stage("Build"){
            steps{
                dir("simple-java-maven-app"){
                sh '''
                    export JAVA_HOME=/usr/local/opt/openjdk@17
                    export PATH=$JAVA_HOME/bin:$PATH
                    /usr/local/Cellar/maven/3.9.9/libexec/bin/mvn clean install
                '''
                }
            }
        }
        stage("Test"){
            steps{
                dir("simple-java-maven-app"){
                    sh '''
                    export JAVA_HOME=/usr/local/opt/openjdk@17
                    export PATH=$JAVA_HOME/bin:$PATH
                    /usr/local/Cellar/maven/3.9.9/libexec/bin/mvn test
                '''
                }
            }
        }

    }
}

